# Generated by Django 4.2.5 on 2025-09-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tourist_Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Guide_Username', models.CharField(max_length=150, unique=True)),
                ('Guide_PassWord', models.CharField(max_length=150)),
                ('Guide_Mail_id', models.EmailField(max_length=254, unique=True)),
                ('Guide_FullName', models.CharField(max_length=150)),
                ('Guide_experience', models.IntegerField(default=0)),
                ('Guide_Languages_know', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=150, unique=True)),
                ('PassWord', models.CharField(max_length=150)),
                ('Mail_id', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
