# Generated by Django 4.2.5 on 2025-09-22 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikkim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist_guide',
            name='Guide_Gender',
            field=models.CharField(default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='tourist_guide',
            name='Guide_Number',
            field=models.CharField(default='0000000000', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
