# Generated by Django 4.2.5 on 2025-09-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikkim', '0002_tourist_guide_guide_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist_guide',
            name='Guide_Image',
            field=models.ImageField(default=None, upload_to='GuideImages/'),
        ),
    ]
