# Generated by Django 4.2.5 on 2025-09-23 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikkim', '0003_tourist_guide_guide_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='User_Number',
            field=models.CharField(default='0000000000', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
