# Generated by Django 4.2.5 on 2025-09-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikkim', '0006_alter_tourist_guide_guide_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Location',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
