# Generated by Django 4.2.5 on 2025-09-25 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sikkim', '0007_users_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=False)),
                ('G_userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sikkim.tourist_guide')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sikkim.users')),
            ],
        ),
    ]
