# Generated by Django 4.2.5 on 2025-09-26 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikkim', '0008_book_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_guide',
            name='from_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='book_guide',
            name='to_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
