# Generated by Django 4.2.5 on 2025-09-26 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikkim', '0009_book_guide_from_date_book_guide_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourist_guide',
            name='Guide_Number',
            field=models.CharField(default=None, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='users',
            name='User_Number',
            field=models.CharField(default=None, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
