# Generated by Django 4.2.5 on 2025-09-26 17:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sikkim', '0010_alter_tourist_guide_guide_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='User_Number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=1)),
                ('time', models.TimeField()),
                ('trip_details', models.CharField(max_length=200)),
                ('time_status', models.IntegerField(default=0)),
                ('day_status', models.IntegerField(default=0)),
                ('i_guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sikkim.tourist_guide')),
                ('i_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sikkim.users')),
            ],
        ),
    ]
