# Generated by Django 4.2.5 on 2025-09-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikkim', '0011_alter_users_user_number_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='User_Gender',
            field=models.CharField(default=None, max_length=13),
        ),
        migrations.AddField(
            model_name='users',
            name='User_Languages_Know',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='tourist_guide',
            name='Guide_Gender',
            field=models.CharField(default='Male', max_length=13),
        ),
    ]
