# Generated by Django 4.2.5 on 2025-09-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikkim', '0012_users_user_gender_users_user_languages_know_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='User_profile_photo',
            field=models.ImageField(default=None, upload_to='UserImages/'),
        ),
    ]
