# Generated by Django 4.2.5 on 2025-09-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sikkim', '0013_users_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='User_fullName',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
