# Generated by Django 4.2.5 on 2025-09-28 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sikkim', '0014_users_user_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary',
            old_name='day_status',
            new_name='trip_status',
        ),
    ]
